#theme: jekyll-theme-minimal
remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Sam Gehman
  tagline: NLP at UW CSE
  date_format: "%b %-d, %Y"

  social_links:
    twitter: samgehman
    github: thesamuel
    linkedIn: in/samgehman # format: locale/username

